# NumPy

NumPy is a highly flexible, optimized, open-source package meant for array processing. It provides tools for delivering high-end performance while dealing with N-dimensional powerful array objects. It is also beneficial for performing scientific computations, mathematical, and logical operations, sorting operations, I/O functions, basic statistical and linear algebra-based operations along with random simulation and broadcasting functionalities. 

#### NumPy Arrays are considered to be better than Lists
<br>
- Python lists support storing heterogeneous data types whereas NumPy arrays can store datatypes of one nature itself. NumPy provides extra functional capabilities that make operating on its arrays easier which makes NumPy array advantageous in comparison to Python lists as those functions cannot be operated on heterogeneous data. <br>
- NumPy arrays are treated as objects which results in minimal memory usage. Since Python keeps track of objects by creating or deleting them based on the requirements, NumPy objects are also treated the same way. This results in lesser memory wastage. <br>
- NumPy arrays support multi-dimensional arrays. <br>
- NumPy provides various powerful and efficient functions for complex computations on the arrays. <br>
- NumPy also provides various range of functions for BitWise Operations, String Operations, Linear Algebraic operations, Arithmetic operations etc. These are not provided on Python’s default lists.<br>

In [1]:
import numpy as np

In [2]:
# 1-D Array Creation

a = np.array([1,2,3])
print("The NumPy array is: {}, it's dimensions are: {} and it's shape is: {}".format(a, a.ndim, a.shape))

The NumPy array is: [1 2 3], it's dimensions are: 1 and it's shape is: (3,)


In [3]:
# Multi-Dimensional Arrays --> List of Lists

a = np.array([[1,2,3],[4,5,6]])
print(a)
print("Dimensions: ",a.ndim)
print("Shape: ",a.shape)

[[1 2 3]
 [4 5 6]]
Dimensions:  2
Shape:  (2, 3)


In [4]:
# Data Types

a = np.array([1,2,3])
print("The NumPy array is: {} and it's data type is: {}".format(a, a.dtype))

a = np.array([1.0,2,3])  #NumPy automatically converts integers to floats
print("The NumPy array is: {} and it's data type is: {}".format(a, a.dtype))

The NumPy array is: [1 2 3] and it's data type is: int32
The NumPy array is: [1. 2. 3.] and it's data type is: float64


### Basic NumPy Functions

In [5]:
# Creating two arrays with same shape but different filler values ( 1 or 0)
a = np.zeros((2,3))
b = np.ones((2,3))
print("Zero-Filled Array: \n",a)
print(" \n One-Filled Array: \n",b)


# Creating an array with random numbers
a = np.random.rand(2,3)
print("\n Randomly Generated Array: \n",a)


# Creating a sequence of numbers in an array with the arange() function
# Syntax :    np.arange(START, END (exclusive) , STEP)
a = np.arange(10,50,5)
print("\n Sequenced Array: \n",a)


# Creating a sequence of floats by using linsapce() function
# Syntax :   np.linspace(START, STOP (inclusive), NUMBER OF ITEMS TO BE GENERATED)
a = np.linspace(0,2,15)
print("\n Linspaced Array: \n",a)

Zero-Filled Array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
 
 One-Filled Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]

 Randomly Generated Array: 
 [[0.41722574 0.80598066 0.36854816]
 [0.2346382  0.3468775  0.58942771]]

 Sequenced Array: 
 [10 15 20 25 30 35 40 45]

 Linspaced Array: 
 [0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.         1.14285714 1.28571429 1.42857143 1.57142857
 1.71428571 1.85714286 2.        ]


In [6]:
# Reversing an Array

# Slicing Method
a = np.array([-3,-2,-1,0,1,2,3])
print("\n Array : \n",a)
print("\n Reversed Array: \n",a[::-1])

# flipud Function
a = np.array([-3,-2,-1,0,1,2,3])
print("\n Array : \n",a)
print("\n Reversed Array: \n",np.flipud(a))


 Array : 
 [-3 -2 -1  0  1  2  3]

 Reversed Array: 
 [ 3  2  1  0 -1 -2 -3]

 Array : 
 [-3 -2 -1  0  1  2  3]

 Reversed Array: 
 [ 3  2  1  0 -1 -2 -3]


In [7]:
# Flip functions on Multi-dimensional Arrays

a = np.array([[1,2,3],[10,20,30],[100,200,300]])
print("\n Array : \n",a)
print("\n Using flipud (up-down) : \n",np.flipud(a))

a = np.array([[1,2,3],[10,20,30],[100,200,300]])
print("\n Using fliplr (left-right) : \n",np.fliplr(a))


 Array : 
 [[  1   2   3]
 [ 10  20  30]
 [100 200 300]]

 Using flipud (up-down) : 
 [[100 200 300]
 [ 10  20  30]
 [  1   2   3]]

 Using fliplr (left-right) : 
 [[  3   2   1]
 [ 30  20  10]
 [300 200 100]]


In [8]:
# Mean() and Average()

# The np.mean() method returns the arithmetic mean, but the np.average() function returns 
# the algebraic mean if no additional parameters are specified, but may also be used to compute a weighted average.

a = np.array([1, 2, 3, 4])
print("\n Array : \n",a)

print("\n Using Mean() : \n", np.mean(a))

print("\n Using Average() without weights: \n", np.average(a))

print("\n Using Average() with weights: \n", np.average(a, weights=(0,0,1,1)))


 Array : 
 [1 2 3 4]

 Using Mean() : 
 2.5

 Using Average() without weights: 
 2.5

 Using Average() with weights: 
 3.5


### Array Operations

In [9]:
# Arithmetic Operators are applied element-wise

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print("\n First Array: \n", a)
print("\n Second Array: \n", b)
print("\n Sum: \n", a+b)
print("\n Difference: \n",a-b)
print("\n Product: \n",a*b)
print("\n Division: \n",a/b)
print("\n Exponential Power: \n",a**b)


 First Array: 
 [10 20 30 40]

 Second Array: 
 [1 2 3 4]

 Sum: 
 [11 22 33 44]

 Difference: 
 [ 9 18 27 36]

 Product: 
 [ 10  40  90 160]

 Division: 
 [10. 10. 10. 10.]

 Exponential Power: 
 [     10     400   27000 2560000]


In [10]:
# Using Array arithmetics to convert data into desired forms

farenheit_temp = np.array([0,-10,-5,-15,0])
celcius_temp = (farenheit_temp - 32)*(5/9)
celcius_temp

array([-17.77777778, -23.33333333, -20.55555556, -26.11111111,
       -17.77777778])

In [11]:
# Boolean Operations

a = np.array([-3,-2,-1,0,1,2,3])
print("\n Array : \n",a)
print("\n Elements Greater than 0 : \n",a>0)
print("\n Elements Greater than or equal to 0 : \n",a>=0)
print("\n Even Elements : \n",a%2 ==0)


 Array : 
 [-3 -2 -1  0  1  2  3]

 Elements Greater than 0 : 
 [False False False False  True  True  True]

 Elements Greater than or equal to 0 : 
 [False False False  True  True  True  True]

 Even Elements : 
 [False  True False  True False  True False]


### Matrix Manipulation

In [12]:
# Normal Element-wise product is obtained by using the "*" operator
# Matrix Multiplication (dot product) is obtained by using the "@" operator

a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])

print("First Array: \n",a)
print("\n Second Array: \n",b)
print("\n Element-wise multiplication : \n", a*b)
print("\n Matrix multiplication : \n", a@b)


First Array: 
 [[1 1]
 [0 1]]

 Second Array: 
 [[2 0]
 [3 4]]

 Element-wise multiplication : 
 [[2 0]
 [0 4]]

 Matrix multiplication : 
 [[5 4]
 [3 4]]


In [13]:
# Upcasting

# When manipulating arrays of differnt types, the type of the resulting array will 
# correspond to the more general of the to types. This is called Upcasting.

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7.1,8.2,9.1],[10.4,11.2,12.3]])

print("\n First Array: \n",a)
print("\n Second Array: \n",b)

print("\n First Array datatype: ",a.dtype)
print("\n Second Array datatype: ",b.dtype)

print("\n Sum Array: \n",a+b)
print("\n Sum Array datatype: ",(a+b).dtype)


 First Array: 
 [[1 2 3]
 [4 5 6]]

 Second Array: 
 [[ 7.1  8.2  9.1]
 [10.4 11.2 12.3]]

 First Array datatype:  int32

 Second Array datatype:  float64

 Sum Array: 
 [[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]

 Sum Array datatype:  float64


### Matrix Slicing and Indexing

In [14]:
# Matrix Slicing 
# Syntax =     ARRAY[ROWS,COLUMNS]
#              ARRAY[x]  --> x corresponds to rows

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n Array : \n",a)

# Accessing a specific element (starting at 0)
print("\n (2,2) element is: \n", a[2,2])

# Slicing using Array[x] --> works on rows by default
print("\n a[0] is: \n", a[0])
print("\n a[:2] is: \n", a[:2])  # 2 is excluded

# Slicing using Array[rows,columns]
print("\n a[1,1] is: \n", a[1,1])
print("\n a[:2,1] is: \n", a[:2,1])
print("\n a[:2,1:2] is: \n", a[:2,1:2])


 Array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 (2,2) element is: 
 9

 a[0] is: 
 [1 2 3]

 a[:2] is: 
 [[1 2 3]
 [4 5 6]]

 a[1,1] is: 
 5

 a[:2,1] is: 
 [2 5]

 a[:2,1:2] is: 
 [[2]
 [5]]


In [15]:
# Accessing multiple elements

a = np.array([[1,2,3],[10,20,30],[100,200,300]])
print("\n Array : \n",a)

# Method 1 - extracting singular elements and placing them into an array
print("\n Method 1 for extracting 1,20 and 300: \n", np.array([a[0,0], a[1,1], a[2,2]]))

# Method 2 - Zips first list and the second list (consider these lists as x and y coordinate lists)
print("\n Method 2 for extracting 1,20 and 300: \n", a[[0,1,2],[0,1,2]])


 Array : 
 [[  1   2   3]
 [ 10  20  30]
 [100 200 300]]

 Method 1 for extracting 1,20 and 300: 
 [  1  20 300]

 Method 2 for extracting 1,20 and 300: 
 [  1  20 300]


In [16]:
# Boolean Indexing

a = np.array([[1,2,3],[10,20,30],[100,200,300]])
print("\n Array : \n",a)

print("\n Boolean Matrix of elements greater than 25 : \n",a>25)

print("\n Matrix of elements greater than 25 : \n", a[a>25])


 Array : 
 [[  1   2   3]
 [ 10  20  30]
 [100 200 300]]

 Boolean Matrix of elements greater than 25 : 
 [[False False False]
 [False False  True]
 [ True  True  True]]

 Matrix of elements greater than 25 : 
 [ 30 100 200 300]


In [17]:
# Updating the Slice of an array also updates the original array

a = np.array([[1,2,3],[10,20,30],[100,200,300]])
print("\n Array : \n",a)

b = a[:2,:2]
print("\n Sub-Array : \n",b)

# Updating Sub-Array
b[0,0] = 1000
print("\n Updating sub-array such that b[0,0] = 1000")

# Updated Sub-Array
print("\n Updated Sub-Array : \n",b)

# Updated Original Array
print("\n Updated Original Array : \n",a)


 Array : 
 [[  1   2   3]
 [ 10  20  30]
 [100 200 300]]

 Sub-Array : 
 [[ 1  2]
 [10 20]]

 Updating sub-array such that b[0,0] = 1000

 Updated Sub-Array : 
 [[1000    2]
 [  10   20]]

 Updated Original Array : 
 [[1000    2    3]
 [  10   20   30]
 [ 100  200  300]]
